# yaml configuration file for running HSJ algorithm

config_name: "hop-skip-jump"
model_interface: pypsa
cost_slack: 0.1
alternatives: 5
spatially_explicit: False
diversified_technologies: ["wind", "solar", "gas", "battery"]
